name: Micronaut Build & Test

on:
  pull_request:
    types: [closed]  
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: mn_playground
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          
      - name: Grant Execute Permission for Gradle
        run: chmod +x gradlew

      - name: Build & Run Tests
        run: ./gradlew build

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: micronaut-crud-jar
          path: build/libs/*.jar

      - name: Deploy to AWS S3
        if: success()
        env:
          AWS_ACCESS_KEY_ID: ASIAR5YGFGNNFWJYUQVP
          AWS_SECRET_ACCESS_KEY: qwkeBwwwUPt0144JZ7Sa6wV6H+H7C7WzTfsDSQJE
          AWS_SESSION_TOKEN: IQoJb3JpZ2luX2VjEM3//////////wEaCXVzLXdlc3QtMiJHMEUCIBkHPrhzXzdKzpF3wqHRgi3rRnC+YBxL58jOAdehruFPAiEAh/hpVAjUwAflvkZ6DKormIrtRKsg33jryHmf4RAJTbQqrwII5v//////////ARACGgwxMzI2MjAwMzkwMDIiDO8tWETgTATn5fMNhiqDArMxXp4QbWcMDhYzLbAnt3RmvvTnAbFlZwYGF5MF03BMdx6tItBdfZwsM1/vu9EWOqSVFh2sYHfqKPgPlJjV/zL3P4Hw8UOsxmJT/sVDIFOm50P+Tx3jLcKZ5VrNF9dN+e5Kq1cmZRfFP8FbPtgpW0aepY3IjcATFTGg8YleNumapY07eYbVzG0iy8jt5N+FaipA2jFfwFzK6hzzoXvQCkjZRA/f5vWsIrkGVFga1BRMKuT2IIbViTEYM+TtmLUY+soY+VjRTsDCWuFqUFmXH6quqYZZw8Z6aY09m1hC0pEl6zRYoK9l8mvEJbmFaCPSas1jFyLoU2fUDPij7N+7rnD4sgwwisywvQY6nQH1ZK/7/utcvHuA4UQSwzNgfhoGIdhi8kGkbNf+BRju3VdkNKyMy0U7z/1kNvDAeERPvOvsrbKR8J60GsubzIDr0FMRSRDUGLxQ9176DOj3N8cSGNyne/SxGGgKaaGZJ6tvxc2untzYVdcs0+OSiugbIBVMabm87weuQt/cDGao0o1i6Dpa/fbn6GHFNprIt+tnI7dpNxUDQBaLdu1u
          AWS_REGION: "us-east-1"
          S3_BUCKET: "assignment6buckets"
        run: aws s3 cp build/libs/ s3://$S3_BUCKET/ --recursive
